// AudioSource discriminated union — no nullable fields, TypeScript exhaustive-checks each branch.
// To swap in a real file: { type: 'local', asset: require('@/assets/audio/file.mp3') }
// To stream remotely:     { type: 'remote', uri: 'https://cdn.example.com/file.mp3' }
export type AudioSource =
  | { type: 'local'; asset: number }
  | { type: 'remote'; uri: string };

export interface ScriptLine {
  text: string;     // language-agnostic; add a second array for multi-language support
  startMs: number;  // milliseconds from audio start
}

export interface Track {
  id: string;
  title: string;
  subtitle: string;
  audio: AudioSource;
  script: ScriptLine[];
  isPremium?: boolean;
  durationLabel?: string;  // display string e.g. "18 phút"; computed from audio at runtime
}

// Seed data — replace with a useTracks() Supabase hook when ready.
// PlayerScreen and HomeScreen will not need to change.
export const TRACKS: Track[] = [
  {
    id: 'chu-dai-bi',
    title: 'Chú Đại Bi',
    subtitle: 'Great Compassion Mantra · 84 câu',
    // Swap to local once the file is in assets/audio/:
    audio: { type: 'local', asset: require('@/assets/audio/chu_dai_bi.mp3') },
    // audio: { type: 'remote', uri: '' },
    durationLabel: '18 phút',
    script: [
      { text: 'Nam mô Đại bi Hội Thượng Phật Bồ tát', startMs: 12000 },
      { text: 'Nam mô Đại bi Hội Thượng Phật Bồ tát', startMs: 19000 },
      { text: 'Nam mô Đại bi Hội Thượng Phật Bồ tát', startMs: 24000 },
      { text: 'Thiên thủ thiên nhãn vô ngại Đại Bi Tâm Đà La Ni', startMs: 35000 },
      { text: 'Nam mô hắc ra đát na đa ra dạ da', startMs: 39000 },
      { text: 'Nam mô a rị da bà lô kiết đế thước bát ra da', startMs: 43000 },
      { text: 'Bồ đề tát đỏa bà da', startMs: 47000 },
      { text: 'Ma ha tát đỏa bà da', startMs: 52000 },
      { text: 'Ma ha ca lô ni ca da', startMs: 55000 },
      { text: 'Án tát bàn ra phạt duệ số đát na đát tỏa', startMs: 57000 },
      { text: 'Nam mô tất kiết lật đỏa y mông a rị da', startMs: 62000 },
      { text: 'Bà lô kiết đế thất Phật ra lăng đà bà', startMs: 64000 },
      { text: 'Nam mô na ra cẩn trì hê rị', startMs: 70000 },
      { text: 'Ma ha bàn đa sa mế,', startMs: 73000 },
      { text: 'tát bà a tha đậu du bằng', startMs: 75000 },
      { text: 'A thệ dựng, tát bà tát đa na ma bà dà,', startMs:  78000},
      { text: 'Ma phạt đạt đậu, đát điệt tha', startMs:  81000},
      { text: 'Án, a bà lô hê', startMs: 83000 },
      { text: 'Lô ca đế, ca ra đế', startMs: 86000 },
      { text: 'Di hê rị, ma ha bồ đề tát đỏa, tát bà tát bà', startMs:  89000},
      { text: 'Ma ra ma ra, ma hê ma hê, rị đà dựng', startMs:  94000},
      { text: 'Cu lô cu lô, kiết mông độ lô độ lô', startMs:  97000},
      { text: 'phạt xà da đế, ma ha phạt xà da đế.', startMs:  100000},
      { text: 'Đà ra đà ra, địa rị ni,', startMs: 106000 },
      { text: 'Thất Phật ra da, giá ra giá ra', startMs: 108000 },
      { text: 'Mạ mạ phạt ma ra, mục đế lệ,', startMs:  111000},
      { text: 'Y hê di hê, thất na thất na', startMs:  113000},
      { text: 'A ra sâm Phật ra xá lợi,', startMs:  116000},
      { text: 'Phạt sa phạt sâm, Phật ra xá da', startMs:  119000},
      { text: 'Hô lô hô lô, ma ra', startMs:  121000},
      { text: 'Hô lô hô lô hê rị, ta ra ta ra,', startMs:  125000},
      { text: 'Tất rị tất rị, tô rô tô rô,', startMs:  129000},
      { text: 'Bồ đề dạ, bồ đề dạ, bồ đà dạ, bồ đà dạ,', startMs:  131000},
      { text: 'Di đế rị dạ na ra cẩn trì', startMs:  136000},
      { text: 'địa rị sắc ni na', startMs:  138000},
      { text: 'Ba dạ ma na, ta bà ha', startMs:  140000},
      { text: 'Tất đà dạ, ta bà ha. Ma ha tất đà dạ, ta bà ha', startMs:  144000},
      { text: 'Tất đà du nghệ, thất bàn ra dạ, ta bà ha.', startMs:  147000},
      { text: 'Na ra cẩn trì, ta bà ha.', startMs:  151000},
      { text: 'Ma ra na ra, ta bà ha.', startMs:  154000},
      { text: 'Tất ra tăng a mục khê da, ta bà ha.', startMs:  156000},
      { text: 'Ta bà ma ha, a tất đà dạ, ta bà ha.', startMs:  160000},
      { text: 'Giả kiết ra a tất đà dạ, ta bà ha.', startMs:  165000},
      { text: 'Ba đà ma yết tất đà dạ, ta bà ha.', startMs:  168000},
      { text: 'Na ra cẩn trì bàn đà ra dạ, ta bà ha.', startMs:  172000},
      { text: 'Ma bà lị thắng yết ra dạ, ta bà ha.', startMs:  176000},
      { text: 'Nam mô hắc ra đát na, đa ra dạ da.', startMs:  181000},
      { text: 'Nam mô a rị da, bà lô kiết đế, ', startMs:  184000},
      { text: 'Thước bàng ra dạ, ta bà ha.', startMs:  187000},
      { text: 'Án, tất điện đô, mạn đa ra,bạt đà dạ ta bà ha.', startMs: 190000 },
      { text: 'Án, tất điện đô, mạn đa ra,bạt đà dạ ta bà ha.', startMs: 196000 },
      { text: 'Án, tất điện đô, mạn đa ra,bạt đà dạ ta bà ha.', startMs:  200000},
      //ver 2
      { text: 'Thiên thủ thiên nhãn vô ngại Đại Bi Tâm Đà La Ni', startMs: 209000 },
      { text: 'Nam mô hắc ra đát na đa ra dạ da', startMs: 215000 },
      { text: 'Nam mô a rị da bà lô kiết đế thước bát ra da', startMs: 218000 },
      { text: 'Bồ đề tát đỏa bà da', startMs: 224000 },
      { text: 'Ma ha tát đỏa bà da', startMs: 228000 },
      { text: 'Ma ha ca lô ni ca da', startMs: 230000 },
      { text: 'Án tát bàn ra phạt duệ số đát na đát tỏa', startMs: 232000 },
      { text: 'Nam mô tất kiết lật đỏa y mông a rị da', startMs: 234000 },
      { text: 'Bà lô kiết đế thất Phật ra lăng đà bà', startMs: 239000 },
      { text: 'Nam mô na ra cẩn trì hê rị', startMs: 244000 },
      { text: 'Ma ha bàn đa sa mế, tát bà a tha đậu du bằng', startMs:  249000},
      { text: 'A thệ dựng, tát bà tát đa na ma bà già,', startMs:  253000},
      { text: 'Ma phạt đạt đậu, đát điệt tha', startMs:  257000},
      { text: 'Án, a bà lô hê', startMs: 259000 },
      { text: 'Lô ca đế, ca ra đế', startMs: 262000 },
      { text: 'Di hê rị, ma ha bồ đề tát đỏa, tát bà tát bà', startMs: 265000},
      { text: 'Ma ra ma ra, ma hê ma hê, rị đà dựng', startMs: 269000},
      { text: 'Cu lô cu lô, kiết mông độ lô độ lô', startMs: 273000},
      { text: 'Phạt xà da đế, ma ha phạt xà da đế.', startMs: 277000},
      { text: 'Đà ra đà ra, địa rị ni', startMs: 282000 },
      { text: 'Thất Phật ra da, giá ra giá ra', startMs: 284000},
      { text: 'Mạ mạ phạt ma ra, mục đế lệ', startMs: 286000},
      { text: 'Y hê di hê, thất na thất na', startMs: 289000},
      { text: 'A ra sâm Phật ra xá lợi,', startMs: 292000},
      { text: 'Phạt sa phạt sâm, Phật ra xá da', startMs: 294000},
      { text: 'Hô lô hô lô, ma ra', startMs: 296000},
      { text: 'Hô lô hô lô hê rị, ta ra ta ra,', startMs:  301000},
      { text: 'Tất rị tất rị, tô rô tô rô,', startMs:  304000},
      { text: 'Bồ đề dạ, bồ đề dạ, bồ đà dạ, bồ đà dạ,', startMs:  307000},
      { text: 'Di đế rị dạ na ra cẩn trì', startMs:  311000},
      { text: 'Địa rị sắc ni na', startMs:  314000},
      { text: 'Ba dạ ma na, ta bà ha', startMs:  316000},
      { text: 'Tất đà dạ, ta bà ha.', startMs: 319000 },
      { text: 'Ma ha tất đà dạ, ta bà ha.', startMs:  322000},
      { text: 'Tất đà du nghệ, thất bàn ra dạ, ta bà ha.', startMs:  323000},
      { text: 'Na ra cẩn trì, ta bà ha.', startMs:  328000},
      { text: 'Ma ra na ra, ta bà ha.', startMs:  330000},
      { text: 'Tất ra tăng a mục khê da, ta bà ha.', startMs:  331000},
      { text: 'Ta bà ma ha, a tất đà dạ, ta bà ha.', startMs:  338000},
      { text: 'Giả kiết ra a tất đà dạ, ta bà ha.', startMs:  342000},
      { text: 'Ba đà ma yết tất đà dạ, ta bà ha.', startMs:  345000},
      { text: 'Na ra cẩn trì bàn đà ra dạ, ta bà ha.', startMs:  348000},
      { text: 'Ma bà lị thắng yết ra dạ, ta bà ha.', startMs:  353000},
      { text: 'Nam mô hắc ra đát na, đa ra dạ da.', startMs:  357000},
      { text: 'Nam mô a rị da, bà lô yết đế, ', startMs:  360000},
      { text: 'Thước bàng ra dạ, ta bà ha.', startMs:  363000},
      { text: 'Án, tất điện đô, mạn đa ra,bạt đà dạ ta bà ha.', startMs: 365000 },
      { text: 'Án, tất điện đô, mạn đa ra,bạt đà dạ ta bà ha.', startMs: 372000 },
      { text: 'Án, tất điện đô, mạn đa ra,bạt đà dạ ta bà ha.', startMs: 377000 },
      // ver 3
      { text: 'Thiên thủ thiên nhãn vô ngại Đại Bi Tâm Đà La Ni', startMs: 384000 },
      { text: 'Nam mô hắc ra đát na đa ra dạ da', startMs: 391000 },
      { text: 'Nam mô a rị da bà lô Yết đế thước bát ra da', startMs: 395000 },
      { text: 'Bồ đề tát đỏa bà da', startMs: 400000 },
      { text: 'Ma ha tát đỏa bà da', startMs: 404000 },
      { text: 'Ma ha ca lô ni ca da', startMs: 406000 },
      { text: 'Án tát bàn ra phạt duệ số đát na đát tỏa', startMs: 408000 },
      { text: 'Nam mô tất kiết lật đỏa y mông a rị da', startMs: 412000 },
      { text: 'Bà lô Yết đế thất Phật ra lăng đà bà', startMs: 416000 },
      { text: 'Nam mô na ra cẩn trì hê rị', startMs: 422000 },
      { text: 'Ma ha bàn đa sa mế, tát bà a tha đậu du bằng', startMs:  425000},
      { text: 'A thệ dựng, tát bà tát đa na ma bà già,', startMs:  429000},
      { text: 'Ma phạt đạt đậu, đát điệt tha', startMs:  433000},
      { text: 'Án, a bà lô hê', startMs: 435000 },
      { text: 'Lô ca đế, ca ra đế', startMs: 439000 },
      { text: 'Di hê rị, ma ha bồ đề tát đỏa, tát bà tát bà', startMs:  441000},
      { text: 'Ma ra ma ra, ma hê ma hê, rị đà dựng', startMs:  445000},
      { text: 'Cu lô cu lô, kiết mông', startMs:  448000},
      { text: 'Độ lô độ lô phạt xà da đế', startMs: 449000 },
      { text: 'Ma ha phạt xà da đế.', startMs:  453000 },
      { text: 'Đà ra đà ra, địa rị ni', startMs: 458000 },
      { text: 'Thất Phật ra da, dá ra dá ra,', startMs: 460000},
      { text: 'Mạ mạ phạt ma ra, mục đế lệ,', startMs:  463000},
      { text: 'Y hê di hê, thất na thất na', startMs:  465000},
      { text: 'A ra sâm Phật ra xá lợi,', startMs:  468000},
      { text: 'Phạt sa phạt sâm, Phật ra xá da', startMs:  470000},
      { text: 'Hô lô hô lô, ma ra', startMs:  472000},
      { text: 'Hô lô hô lô hê rị, ta ra ta ra,', startMs:  477000},
      { text: 'Tất rị tất rị, tô rô tô rô,', startMs:  480000},
      { text: 'Bồ đề dạ, bồ đề dạ, bồ đà dạ, bồ đà dạ,', startMs:  483000},
      { text: 'Di đế rị dạ na ra cẩn trì', startMs:  487000},
      { text: 'Địa rị sắc ni na', startMs:  489000},
      { text: 'Ba dạ ma na, ta bà ha', startMs:  491000},
      { text: 'Tất đà dạ, ta bà ha.', startMs: 495000 },
      { text: 'Ma ha tất đà dạ, ta bà ha.', startMs:  497000},
      { text: 'Tất đà du nghệ, thất bàn ra dạ, ta bà ha.', startMs:  500000},
      { text: 'Na ra cẩn trì, ta bà ha.', startMs:  503000},
      { text: 'Ma ra na ra, ta bà ha.', startMs:  506000},
      { text: 'Tất ra tăng a mục khê da, ta bà ha.', startMs:  508000},
      { text: 'Ta bà ma ha, a tất đà dạ, ta bà ha.', startMs:  514000},
      { text: 'Giả kiết ra a tất đà dạ, ta bà ha.', startMs:  517000},
      { text: 'Ba đà ma yết tất đà dạ, ta bà ha.', startMs:  520000},
      { text: 'Na ra cẩn trì bàn đà ra dạ, ta bà ha.', startMs:  524000},
      { text: 'Ma bà lị thắng yết ra dạ, ta bà ha.', startMs:  529000},
      { text: 'Nam mô hắc ra đát na, đa ra dạ da.', startMs:  532000},
      { text: 'Nam mô a rị da, bà lô yết đế, ', startMs:  535000},
      { text: 'Thước bàng ra dạ, ta bà ha.', startMs:  538000},
      { text: 'Án, tất điện đô, mạn đa ra,bạt đà dạ ta bà ha.', startMs: 540000 },
      { text: 'Án, tất điện đô, mạn đa ra,bạt đà dạ ta bà ha.', startMs: 548000 },
      { text: 'Án, tất điện đô, mạn đa ra,bạt đà dạ ta bà ha.', startMs: 553000 },
    ],
  },
  {
    id: 'nam-mo-a-di-da-phat',
    title: 'Nam Mô A Di Đà Phật',
    subtitle: 'Amitabha Recitation',
    audio: { type: 'remote', uri: '' },
    durationLabel: '10 phút',
    script: [],
  },
  {
    id: 'kinh-bat-nha',
    title: 'Kinh Bát Nhã',
    subtitle: 'Heart Sutra',
    audio: { type: 'remote', uri: '' },
    durationLabel: '8 phút',
    isPremium: true,
    script: [],
  },
  {
    id: 'than-chu-cau-an',
    title: 'Thần Chú Cầu An',
    subtitle: 'Protection Mantra',
    audio: { type: 'remote', uri: '' },
    durationLabel: '22 phút',
    isPremium: true,
    script: [],
  },
  {
    id: 'kinh-phap-hoa',
    title: 'Kinh Pháp Hoa',
    subtitle: 'Lotus Sutra',
    audio: { type: 'remote', uri: '' },
    durationLabel: '30 phút',
    isPremium: true,
    script: [],
  },
  {
    id: 'kinh-dia-tang',
    title: 'Kinh Địa Tạng',
    subtitle: 'Ksitigarbha Sutra',
    audio: { type: 'remote', uri: '' },
    durationLabel: '45 phút',
    isPremium: true,
    script: [],
  },
  {
    id: 'bai-sam-hoi',
    title: 'Bài Sám Hối',
    subtitle: 'Repentance Chant',
    audio: { type: 'remote', uri: '' },
    durationLabel: '15 phút',
    script: [],
  },
  {
    id: 'kinh-vo-luong-tho',
    title: 'Kinh Vô Lượng Thọ',
    subtitle: 'Amitayus Sutra',
    audio: { type: 'remote', uri: '' },
    durationLabel: '60 phút',
    isPremium: true,
    script: [],
  },
  {
    id: 'chú-dai-bi-ngan-gon',
    title: 'Chú Đại Bi Ngắn',
    subtitle: 'Short Great Compassion Mantra',
    audio: { type: 'remote', uri: '' },
    durationLabel: '5 phút',
    script: [],
  },
  {
    id: 'kinh-a-di-da',
    title: 'Kinh A Di Đà',
    subtitle: 'Amitabha Sutra',
    audio: { type: 'remote', uri: '' },
    durationLabel: '20 phút',
    script: [],
  },
  {
    id: 'thap-nhi-nguyen',
    title: 'Thập Nhị Nguyện',
    subtitle: 'Twelve Vows',
    audio: { type: 'remote', uri: '' },
    durationLabel: '12 phút',
    isPremium: true,
    script: [],
  },
];
